---
sudo: required
language: generic
dist: xenial

env:
  - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"

before_install:
  # On Pull commit to master, build the helm repo
  - echo "Install helm"
  - cat /etc/*release*
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only

   
install:
  # Package for release 
  - echo "In Install path"
  - mkdir -p repo/stable
  - helm package stable/ibm-nginx-dev -d repo/stable
